## Introduction to Supervised Learning

#### >> Learning Objectives
• Explain supervised learning and how it can be applied to 
regression and classification problems.

• Apply K-Nearest Neighbor (KNN) algorithm for 
classification.

• Apply Intel® Extension for Scikit-learn* to leverage 
underlying compute capabilities of hardware


### Feature Scaling: The Syntax
##### **Import the class containing the scaling method**

In [1]:
from sklearn.preprocessing import StandardScaler

##### **Create an instance of the class**

In [2]:
StdSc = StandardScaler()

##### **data**

In [3]:
# Sample data
data = {
    'Feature1': [10, 20, 30, 40, 50],
    'Feature2': [100, 200, 300, 400, 500],
    'Feature3': [1000, 2000, 3000, 4000, 5000]
}

##### **Create a DataFrame**

In [4]:
import pandas as pd
X_data = pd.DataFrame(data)
print("Original Data:")
print(X_data)

Original Data:
   Feature1  Feature2  Feature3
0        10       100      1000
1        20       200      2000
2        30       300      3000
3        40       400      4000
4        50       500      5000


##### **Fit the scaling parameters and then transform the data**

In [5]:

StdSc = StdSc.fit(X_data)
print("StdSc")
print(StdSc)

StdSc
StandardScaler()


In [6]:
X_scaled = StdSc.transform(X_data)
print(X_scaled)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


##### **Convert the scaled data back to a DataFrame for better readability**

In [7]:
X_scaled_df = pd.DataFrame(X_scaled, columns=X_data.columns)
print("\nScaled Data:")
print(X_scaled_df)


Scaled Data:
   Feature1  Feature2  Feature3
0 -1.414214 -1.414214 -1.414214
1 -0.707107 -0.707107 -0.707107
2  0.000000  0.000000  0.000000
3  0.707107  0.707107  0.707107
4  1.414214  1.414214  1.414214


##### **MinMaxScaler**
The `MinMaxScaler` scales the data to a specified range, typically between 0 and 1.

In [9]:
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler

In [10]:
minmax_scaler = MinMaxScaler()
X_minmax_scaled = minmax_scaler.fit_transform(X_data)
X_minmax_scaled_df = pd.DataFrame(X_minmax_scaled, columns=X_data.columns)
print("\nMinMax Scaled Data:")
print(X_minmax_scaled_df)


MinMax Scaled Data:
   Feature1  Feature2  Feature3
0      0.00      0.00      0.00
1      0.25      0.25      0.25
2      0.50      0.50      0.50
3      0.75      0.75      0.75
4      1.00      1.00      1.00


##### **MaxAbsScaler**
The `MaxAbsScaler` scales each feature by its maximum absolute value, preserving the sign of the data.

In [11]:
maxabs_scaler = MaxAbsScaler()
X_maxabs_scaled = maxabs_scaler.fit_transform(X_data)
X_maxabs_scaled_df = pd.DataFrame(X_maxabs_scaled, columns=X_data.columns)
print("\nMaxAbs Scaled Data:")
print(X_maxabs_scaled_df)


MaxAbs Scaled Data:
   Feature1  Feature2  Feature3
0       0.2       0.2       0.2
1       0.4       0.4       0.4
2       0.6       0.6       0.6
3       0.8       0.8       0.8
4       1.0       1.0       1.0


In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Sample data: features and labels
X = np.array([[1, 2], [2, 3], [3, 4], [5, 6], [6, 7], [7, 8]])
y = np.array([0, 0, 0, 1, 1, 1])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Create the KNN classifier
knn = KNeighborsClassifier(n_neighbors=3)

# Train the classifier
knn.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = knn.predict(X_test)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Example prediction
new_data = np.array([[4, 5]])
prediction = knn.predict(new_data)
print(f"Prediction for {new_data}: {prediction}")

Accuracy: 0.00%
Prediction for [[4 5]]: [1]


### Complete